name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
  push:
    branches: ['master']
  #schedule:
    # run once every month
    #- cron: '0 12 15 * *'


jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['8.2', '8.3', '8.4']
        dependency-version: ['prefer-lowest', 'prefer-stable']

    name: Test ${{ matrix.os }} PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
